### ISSUE TITLE
Error when contents is empty

### ISSUE THREAD

**Issue by grabbou** [SBoudrias/detect-conflict#1]
Use case:

Yeoman generator is trying to copy an image from path XXX to YYY. YYY is within the project folder and the conflict should be now resolved. 

Unfortunately, due to the fact that contents is null, buffer throws an error:

``` js
this.length = +subject.length > 0 ? Math.ceil(subject.length) : 0;
TypeError: Cannot read property 'length' of null
    at new Buffer (buffer.js:184:31)
```

Conflict should always be raised if there's something at filePath and new content is null.

**Comment by vjpr** [comment]
This broke when `mem-fs-editor` was bumped from 2.2.0 -> 2.2.1.

**Comment by SBoudrias** [comment]
Oh yeah, I'll try to get some time to fix this tonight.

**Comment by SBoudrias** [comment]
Fixed on master.
